#%RAML 1.0 DataType
properties:
  company_ID:
    type: integer
  cab_Company:
    type: string
  amount:
    type: integer
  source:
    type: string
  destination:
    type: string
  number_Of_Cars_Available:
    type: integer
  date:
    type: date-only
